name: mobile_pdf_editor
description: Multi-page Flutter PDF editor with drawing, images, stamps, undo/redo and Google Drive.
publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  image_picker: ^1.2.3
  pdfrx: ^2.4.7
  pdf: ^3.13.0
  path_provider: ^2.1.5
  share_plus: ^13.2.1
  signature: ^6.3.0
  uuid: ^4.5.2
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0

flutter:
  uses-material-design: true
